### ISSUE TITLE
Emoji Keyboard Height

### ISSUE THREAD

**Issue by VeeraAndroid** [niravkalola/AndroidEmojisKeyboard#1]
Emoji **keyboard height** can not change

![screenshot_2016-03-04-15-42-55](https://cloud.githubusercontent.com/assets/8385761/13524940/18bd68ec-e224-11e5-88d4-4c8b73600d05.png)

**Comment by VeeraAndroid** [comment]
![Uploading Screenshot_2016-03-04-15-42-55.png…]()

**Comment by hhasina** [comment]
See the method `setSizeForSoftKeyboard()` in `EmojiconsPopup.class` and you can add an additional height to emojicons popup : 
`keyBoardHeight = heightDifference + mContext.getResources().getDimensionPixelSize(R.dimen.additional_keyboard_height); `
